# Generated by Django 5.0.1 on 2024-01-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModelMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('basemodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.basemodelmixin')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанія',
            },
            bases=('games.basemodelmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('basemodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.basemodelmixin')),
                ('description', models.TextField(null=True, verbose_name='Описання')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='game_poster/', verbose_name='Постер')),
                ('steam', models.URLField(blank=True, null=True, verbose_name='Steam')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('game_file', models.FileField(blank=True, null=True, upload_to='game_files/', verbose_name='Файли з грою')),
                ('country', models.CharField(max_length=120, null=True, verbose_name='Країна')),
                ('release_date', models.PositiveIntegerField(default=2024, verbose_name='Рік')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення поста')),
                ('youtube_video_url', models.URLField(blank=True, null=True, verbose_name='Переглянути в ютубі')),
                ('draft', models.BooleanField(default=False, verbose_name='Чорновик')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.company')),
            ],
            options={
                'verbose_name': 'Ігра',
                'verbose_name_plural': 'Ігри',
            },
            bases=('games.basemodelmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('basemodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.basemodelmixin')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
            },
            bases=('games.basemodelmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('basemodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.basemodelmixin')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформи',
            },
            bases=('games.basemodelmixin', models.Model),
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='game_screenshots/', verbose_name='Зображеня')),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Скріншот',
                'verbose_name_plural': 'Скріншоти',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='game_genres', to='games.genre', verbose_name='Жанри'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='game_platforms', to='games.platform', verbose_name='Платформи'),
        ),
    ]
